### PR TITLE
Add feature to compile protobuf library from source

### PR DESCRIPTION
**Pull request by liamkinne**
This is useful for cross compilation.

### CODE REVIEW

**Comment by tisonkun** [comment]
Thank you! Can we remove `setup-protoc` step with this patch?

**Comment by tisonkun** [comment]
I'm merging this patch first.

You're welcome to figure out if we can remove `setup-protoc` step in the workflows with this patch.

**Comment by tisonkun** [comment]
Thanks for your contribution @liamkinne!

**Comment by liamkinne** [comment]
@tisonkun If its going to cause the build time to go up significantly, it may not be worth it. Will give it a go and report back.

**Comment by tisonkun** [comment]
Thank you!

**Pull request merged**
