### PR TITLE
Fix/ack not sent

### PR DESCRIPTION
**Pull request by dghilardi**
Rewrite `ConsumerEngine::<Exe>::engine` method to better handle events and solve #175 bug.

Basically it introduces a supporting channel to merge `message_rx` and `engine_rx` channels.

### CODE REVIEW

**Comment by FlorentinDUBOIS** [comment]
Hey @dghilardi :wave:, thank you for your contribution. Could you rebase your work on the branch `master`?

**Comment by FlorentinDUBOIS** [comment]
Besides, during a rebase to test the source code, I saw this incoming changes in the `update_topics` which implies to not update anything, if a regex is not set. To me this change should not occurs https://github.com/streamnative/pulsar-rs/blob/f0a99fde280ab794d10c6206eb61a0c5e2514754/src/consumer.rs#L1945

**Comment by dghilardi** [comment]
Hi @FlorentinDUBOIS sorry I didn't see your last message yesterday.
By the way the change you're referring was not wanted, probably was a wrong merge or rebase.
Now I've rebased my branch and looking at the diff is not present anymore.
Please let me know if you need anything else.

**Comment by dghilardi** [comment]
I noticed a possible regression in my code and fixed it

**Comment by yswtrue** [comment]
retch the same problem here, hope to make a new release.

**Review by FlorentinDUBOIS — APPROVED** [review]

**Pull request merged**
