### PR TITLE
#154 expose `message_id` to Message

### LINKED ISSUE #154: Make message_id accessible for a Consumer Message
Currently, the `message_id` field is not accessible but don't we need it if we need to position the cursor to a specific point in the stream?

Happy to submit a PR for this but let me know if I am missing an alternate approach to do this that is already available

Reference: https://github.com/wyyerd/pulsar-rs/blob/master/src/consumer.rs#L1684

### PR DESCRIPTION
**Pull request by freeznet**
fix #154

- pub `message_id` in `Message`
- impl `message_id()`

### CODE REVIEW

**Comment by freeznet** [comment]
@sammoh94 @BewareMyPower please help to review if you have time, thanks.

**Review by BewareMyPower — APPROVED** [review]
LGTM

**Comment by sammoh94** [comment]
LGTM. Thanks!

**Comment by freeznet** [comment]
@Geal PTAL if you have time, thanks.

**Comment by Geal** [comment]
Thanks!

**Pull request merged**
