### PR TITLE
Service discovery

### PR DESCRIPTION
**Pull request by Geal**
current work on adding service discovery support, based on #16

### CODE REVIEW

**Comment by Geal** [comment]
@stearnsc the PR is in a good state now, ready for review. There's a lot of features in there, some of which I'd like to extract elsewhere (like a connection manager that would be usable by SD, consumers and producers), but it's already usable

**Comment by stearnsc** [comment]
This looks great!
My understanding of the new usage is the user:
(1) creates a `ServiceDiscovery`
(2) uses the `ServiceDiscovery` + relevant topic to obtain a `BrokerAddress`
(3) uses the `ServiceDiscovery` + `BrokerAddress` to obtain a `Connection`
(4) uses the `Connection` to create the `Producer` or `Consumer`
(5) uses the `Producer` or `Consumer` to send/receive messages.

That feels like a lot of steps to me; are you anticipating using helpers or similar to simplify the simplest "lookup topic, send messages" flows? Also I'm not sure I grok the `BrokerAddress` abstraction; is your vision that users would cache this somewhere in order to e.g. reconnect? What would users use this for other than immediately turn around and make a `Connection` with it?

(btw these questions are totally not blockers for this PR; I just want to get a sense for your vision)

**Comment by stearnsc** [comment]
Ah sorry I read stuff out of order; lemme read your comments on https://github.com/wyyerd/pulsar-rs/issues/1 and see if it makes sense

**Comment by Geal** [comment]
Also check out #20 for an interface idea that would make all those steps go away :)

**Comment by stearnsc** [comment]
Got it, looks good!

**Pull request merged**
