### PR TITLE
bump prost to 0.11.0

### PR DESCRIPTION
**Pull request by skyzh**
As title. This is a breaking change and also needs to bump and release new version of pulsar-rs. Not sure whether this PR is the best way to bump dependencies. Thanks for reviewing!

### CODE REVIEW

**Comment by fantapsody** [comment]
Could you explain the motivation of the PR? I checked the release note of https://github.com/tokio-rs/prost/releases/tag/v0.11.0 and it didn't mention the version has a breaking change. @skyzh

**Comment by skyzh** [comment]
Generally bumping prost would need to bump major semantic version of projects depending on it to keep APIs consistent and semantic version convention. It would also be okay to only bump a minor version for the pulsar package if we don’t need to follow semantic version convention. This practice is followed by a lot of projects like tonic.

**Comment by skyzh** [comment]
… and Prost’s release note mentions that “Relase 0.11 brings a few breaking changes and changes to how prost sources protoc”, though the change looks minor.

**Comment by skyzh** [comment]
Need to install protoc in CI manually. Will fix CI scripts.

**Comment by skyzh** [comment]
Need approval for workflow. I believe it should work for now.

**Comment by skyzh** [comment]
ready for review

**Comment by tisonkun** [comment]
@skyzh since it requires a major version bump, I'm curious about the motivation of bumping prost version itself.

If we don't see a requirement yet, we can postpone this version bump.

**Comment by skyzh** [comment]
That would be fine, we can do this later.

**Comment by FlorentinDUBOIS** [comment]
Hi, this bump has been done in the pr #233. Thank you for your contribution :)

**Pull request closed without merging**
