### PR TITLE
fix: use runtime agnostic stream

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @lukesteensen

I've tested with:

```
cargo build --no-default-features --features "tokio-runtime"
```

**Review by lukesteensen — APPROVED** [review]
Makes sense to me, thanks @tisonkun!

**Comment by tisonkun** [comment]
Trivial to merge. I'm going to release a 5.0.2 as a patch release...

**Comment by tisonkun** [comment]
Released.

**Comment by lukesteensen** [comment]
Thanks @tisonkun! Appreciate the quick fix.

**Pull request merged**
